# Generated by Django 5.0 on 2024-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabterm",
            name="word",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
