# Generated by Django 5.0 on 2024-01-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_alter_vocabterm_word_delete_word"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabterm",
            name="date_added",
        ),
    ]
